#Security
security:
  # Uncomment for ACL support
  #acl:
  #  connection: default
   
  role_hierarchy:
    ROLE_ADMIN:  [ROLE_USER, ROLE_SONATA_ADMIN]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    SONATA:
      - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # comment it when using acl
   
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username

  encoders:
    FOS\UserBundle\Model\UserInterface: sha512

  firewalls:
    # -> custom firewall for the admin area of the URL
    admin:
      pattern:  /admin(.*)
      context:  user
      form_login:
        provider:  fos_userbundle
        login_path:  /admin/login
        use_forward:  false
        check_path:  /admin/login_check
        failure_path:  null
      logout:
        path:  /admin/logout
      anonymous:  true
    # -> end custom configuration
   
    main:
      pattern: ^/
      form_login:
        provider: fos_userbundle
        csrf_provider: form.csrf_provider
      logout:  true
      anonymous:  true
   
  access_control:
    # URL of FOSUserBundle which need to be available to anonymous users
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/*, role: IS_AUTHENTICATED_FULLY}
    - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }