admin_dashboard_index:
    path:     /
    defaults: { _controller: GarbageCollectorAdminBundle:Dashboard:index }

admin_dashboard_dashboard:
    path:     /dashboard
    defaults: { _controller: GarbageCollectorAdminBundle:Dashboard:dashboard }

admin_garbagecan_list:
    path:     /garbagecan/
    defaults: { _controller: GarbageCollectorAdminBundle:GarbageCan:list }

admin_garbagecan_new:
    path:     /garbagecan/new
    defaults: { _controller: GarbageCollectorAdminBundle:GarbageCan:new }

admin_garbagecan_edit:
    path:     /garbagecan/edit/{id}
    defaults: { _controller: GarbageCollectorAdminBundle:GarbageCan:edit }

admin_garbagecan_show:
    path:     /garbagecan/{id}
    defaults: { _controller: GarbageCollectorAdminBundle:GarbageCan:show }

admin_garbagecan_delete:
    path:     /garbagecan/delete/{id}
    defaults: { _controller: GarbageCollectorAdminBundle:GarbageCan:delete }
    methods:  [DELETE]

admin_housecommittee_new:
    path: /housecommittee/new
    defaults: { _controller: GarbageCollectorAdminBundle:HouseCommittee:new }

admin_housecommittee_edit:
    path: /housecommittee/edit/{id}
    defaults: { _controller: GarbageCollectorAdminBundle:HouseCommittee:edit }

admin_housecommittee_show:
    path:     /housecommittee/{id}
    defaults: { _controller: GarbageCollectorAdminBundle:HouseCommittee:show }

admin_housecommittee_list:
    path:     /housecommittee/
    defaults: { _controller: GarbageCollectorAdminBundle:HouseCommittee:list }
