admin_dashboard_index:
    path:     /
    defaults: { _controller: GarbageCollectorAdminBundle:Dashboard:index }

admin_dashboard_dashboard:
    path:     /dashboard
    defaults: { _controller: GarbageCollectorAdminBundle:Dashboard:dashboard }

admin_garbage_list:
    path:     /garbage/
    defaults: { _controller: GarbageCollectorAdminBundle:Garbage:list }

admin_garbage_new:
    path:     /garbage/new
    defaults: { _controller: GarbageCollectorAdminBundle:Garbage:new }

admin_garbage_edit:
    path:     /garbage/edit/{id}
    defaults: { _controller: GarbageCollectorAdminBundle:Garbage:edit }

admin_garbage_show:
    path:     /garbage/{id}
    defaults: { _controller: GarbageCollectorAdminBundle:Garbage:show }

admin_garbage_delete:
    path:     /garbage/delete/{id}
    defaults: { _controller: GarbageCollectorAdminBundle:Garbage:delete }
    methods:  [DELETE]

